
version: '2'

services:
    odcockpit:
        build: .
        network_mode: "host"
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ~/recordings:/opt/recordings
        - .:/opt/opendlv.data
        ipc: host
        user: odv
        command: "/opt/od4/bin/odcockpit --cid=${CID}"

