# docker-compose.yml - Micro-services to monitor one documentation camera.
# Copyright (C) 2016 Hang Yin, Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

version: '2'

services:
    # Micro-service for odcockpit to monitor a running recording session.
    odcockpit:
        build: .
        environment:
            - DISPLAY=$DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ~/recordings:/opt/recordings
        user: odv
        network_mode: host
        ipc: host
        command: "/opt/od4/bin/odcockpit --cid=${CID}"

