# docker-compose.yml - Composition of micro-services to run OpenDLV software.
# Copyright (C) 2016 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2016-10-16

version: '2'

services:
        
    # micro service for proxy-anglesensor.
    proxy-anglesensor1:
        build: .
        network_mode: "host"
        volumes:
            - .:/opt/opendlv.core.configuration
            - /sys/:/sys/
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-anglesensor --cid=${CID} --freq=10 --id=1"

    # micro service for proxy-anglesensor.
    proxy-anglesensor2:
        build: .
        network_mode: "host"
        volumes:
            - .:/opt/opendlv.core.configuration
            - /sys/:/sys/
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-anglesensor --cid=${CID} --freq=10 --id=2"

    proxy-anglesensor3:
        build: .
        network_mode: "host"
        volumes:
            - .:/opt/opendlv.core.configuration
            - /sys/:/sys/
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-anglesensor --cid=${CID} --freq=10 --id=3"

    proxy-imu8:
        build: .
        devices:
        - "/dev/i2c-2:/dev/i2c-2"
        network_mode: "host"
        volumes:
            - .:/opt/opendlv.core.configuration
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-imu --cid=${CID} --freq=10 --id=8"

    proxy-imu9:
        build: .
        devices:
        - "/dev/i2c-2:/dev/i2c-2"
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.core.configuration
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-imu --cid=${CID} --freq=10 --id=9"


