version: '2'
# Please note that docker-compose does not prescribe a startup order

#This docker-compose file makes camera-proxy and odrecorderh264 run in headless mode, i.e., recording videos without display. In this mode, the debug parameter of proxy-camera in the configuration file needs to be set to 0. If a displayer is available, it is possible to view what is being recorded by (1) setting the debug parameter of proxy-camera in the configuration file to 1; and (2) add the following to services proxy1, proxy2, and proxy3:

#environment:
#- DISPLAY=$DISPLAY
#volumes:
#- /tmp/.X11-unix:/tmp/.X11-unix

#In addition, run "xhost +" to grant access to your Xserver before running docker-compose up.
############################
#Run the following to replay the recordings (or follow the instructions of another use case replay.videos):
#docker run -ti --rm --net=host -v $HOME/recordings:/opt/recordings seresearch/opendavinci-ubuntu-16.04-complete:latest /opt/od4/bin/odsupercomponent --cid=111 --verbose=1  --configuration=/opt/recordings/configuration

#docker run -ti --rm --net=host --ipc=host --user=root -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME/recordings:/opt/recordings seresearch/opendavinci-ubuntu-16.04-complete:latest /opt/od4/bin/odcockpit --cid=111

#docker run -ti --rm --net=host --ipc=host --user=root -v $HOME/recordings:/opt/recordings -w /opt/recordings seresearch/opendavinci-ubuntu-16.04-complete:latest /opt/od4/bin/odplayerh264 --cid=111

services:
    #odsupercomponent
    odsupercomponent:
        build: .
        image: seresearch/opendavinci-ubuntu-16.04-complete:latest
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"
        
    #camera 1
    proxy1:
        build: .
        group_add:
            - video
        ipc: host
        user: odv
        devices:
        - "/dev/video0:/dev/video0"
        links:
            - odsupercomponent
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-camera --cid=${CID}  --id=1 --freq=20"
        
    #camera 2
    proxy2:
        build: .
        group_add:
            - video
        ipc: host
        user: odv
        devices:
        - "/dev/video1:/dev/video1"
        links:
            - odsupercomponent
            - proxy1
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-camera --cid=${CID}  --id=2 --freq=20"
        
    #camera 3
    proxy3:
        build: .
        group_add:
            - video
        ipc: host
        user: odv
        devices:
        - "/dev/video2:/dev/video2"
        links:
            - odsupercomponent
            - proxy1
            - proxy2
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-camera --cid=${CID}  --id=3 --freq=20"
        
    #odrecorderh264
    odrecorderh264:
        build: .
        image: seresearch/opendavinci-ubuntu-16.04-complete:latest
        volumes:
        - ~/recordings:/opt/recordings
        working_dir: "/opt/recordings"
        ipc: host
        user: odv
        links:
            - odsupercomponent
            - proxy1
            - proxy2
            - proxy3
        command: "/opt/od4/bin/odrecorderh264 --cid=${CID}"
        

